// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	model "holistic-herbal-encyclopedia/model"

	mock "github.com/stretchr/testify/mock"
)

// IModel is an autogenerated mock type for the IModel type
type IModel struct {
	mock.Mock
}

// GetAllEntries provides a mock function with given fields:
func (_m *IModel) GetAllEntries() []model.Herb {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllEntries")
	}

	var r0 []model.Herb
	if rf, ok := ret.Get(0).(func() []model.Herb); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Herb)
		}
	}

	return r0
}

// GetEntryByName provides a mock function with given fields: name
func (_m *IModel) GetEntryByName(name string) *model.Herb {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetEntryByName")
	}

	var r0 *model.Herb
	if rf, ok := ret.Get(0).(func(string) *model.Herb); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Herb)
		}
	}

	return r0
}

// GetModel provides a mock function with given fields:
func (_m *IModel) GetModel() *model.Model {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetModel")
	}

	var r0 *model.Model
	if rf, ok := ret.Get(0).(func() *model.Model); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Model)
		}
	}

	return r0
}

// NewEntry provides a mock function with given fields: name, dosage, uses, precautions, preparations
func (_m *IModel) NewEntry(name string, dosage int, uses string, precautions string, preparations string) int64 {
	ret := _m.Called(name, dosage, uses, precautions, preparations)

	if len(ret) == 0 {
		panic("no return value specified for NewEntry")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, int, string, string, string) int64); ok {
		r0 = rf(name, dosage, uses, precautions, preparations)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// NewIModel creates a new instance of IModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *IModel {
	mock := &IModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
